### ISSUE TITLE
Type/info tooltips on selection

### ISSUE THREAD

**Issue by tepf** [atom-haskell/ide-haskell#133]
It would be nice if you could see the type info of the word under the cursor in the completion hint panel as well instead of having to hover it with the mouse.

**Comment by lierdakil** [comment]
Well, it *is* possible to assign a keybinding to show type of selected expression. Querying ghc-mod on every cursor movement would be a bad idea on larger projects.

**Comment by tepf** [comment]
Yes, it might slow things down. But being able to assign a keybinding would be fine as well.

**Comment by lierdakil** [comment]
Well, you could consult https://github.com/atom-haskell/haskell-ghc-mod#keybindings and https://github.com/atom-haskell/ide-haskell#keyboard-shortcuts. Also possibly https://atom.io/docs/v1.3.3/using-atom-basic-customization#customizing-key-bindings

You might also want to fiddle with haskell-ghc-mod settings (which actually provides show type/show info etc functionality) for more fine-grained control over when to show and when to hide type tooltip.

**Comment by rvion** [comment]
@lierdakil on sublime text with `stack-ide-sublime` plugin, there is an option to redisplay the type popup at each cursor move or selection change, and this is just __amazing__ :sunny: (IMHO). stack-ide-backend handles caching perfectly and it's instant even on quite large projects. (I think that a mix of https://github.com/atom-haskell/ide-haskell/issues/62 + improving ghc-mod could be enough to handle large projects correctly)

I'd also like to mention those features in `stack-ide-sublime`

 1. clickable link opening haddock for types:
  ![image](https://cloud.githubusercontent.com/assets/2150990/11168603/f8d7329e-8b96-11e5-94a8-075e1d7e5e72.png)

 2. an option to remove prefixes :sunny:  (this is a must-have too IMHO)
    (with prefixes)
    ![image](https://cloud.githubusercontent.com/assets/2150990/11168146/06ec7bfe-8b84-11e5-8fad-cf4ed72067cd.png)
   
     (without prefixes but with an underscore to tell about hidden prefix: more readable)
    ![image](https://cloud.githubusercontent.com/assets/2150990/11168144/f5bc0ee4-8b83-11e5-9570-1adeee979963.png)

 3. realtime closest enclosing expression display (there is the same thing on atom, but it works slighly better on doesn't work as well):

    <img width="256" alt="capture d ecran 2015-07-28 a 13 39 40" src="https://cloud.githubusercontent.com/assets/2150990/8956232/ed2b2bec-35f3-11e5-920e-1dea3c369093.png">
    <img width="260" alt="capture d ecran 2015-07-28 a 13 39 32" src="https://cloud.githubusercontent.com/assets/2150990/8956231/ed2aee2a-35f3-11e5-94c5-927a0f24ee6c.png">






--------------------



@lierdakil the clickable links + prefix removal is done this way:
 - 2 new settings:
   ```js
  // If "show_popup" is true, a popup will remain visible at all time below cursor / selection
  ,"show_popup": false

  // if show_popup is true, clicking on types displayed in the popup panel will
  // open a web-browser at specified hoogle_url with the right type query.
  // if you set this to your own hoogle webserver setup for your project,
  // you'll be able to see the documentation for your own type
  // example: "hoogle_url": "https://www.google.fr/search?q=what+is+haskell+"
  ,"hoogle_url": "http://www.stackage.org/lts/hoogle?q="
   ```
 - (ugly) python code to format types:
  ```python
def format_type(raw_type):
    words = raw_type.replace("(", " ( ").replace(")", " ) ").replace("[", " [ ").replace("]", " ] ").replace(",", " , ").split(' ')
    return (" ".join(map(format_subtype, words)).replace(" ( ","(").replace(" ) ",")").replace(" [ ","[").replace(" ] ","]").replace(" , ",","))

def format_subtype(type_string):
    # See documentation about popups here:
    #       http://facelessuser.github.io/sublime-markdown-popups/usage/ (official doc)
    # and   https://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583  (html support announcment)

    words = [x for x in type_string.split('.') if x != '']
    # [x for x in type_string.split('.') is necessary to handle the `a.` part of `forall a.` properly

    if (len(words) > 1):
        s = ("_"+words[-1])
    else:
        s = type_string

    if s == "->":
        return ('<span style="color: blue">{0}</span>'.format("->"))
    elif s == "(" or s == ")" or s == "[" or s == "'" or s == "]" or s=='' or s==',':
        return s
    elif (s[0] != '_' and s[0].islower()):
        return ('<span style="color: #4C4C4C">{0}</span>'.format(s))
    else:
        return ('<a href="{0}" style="color: #333333">{1}</a>'.format(type_string.split(":")[-1], s))
```

**Comment by lierdakil** [comment]
@rvion, I think I could manage type/info tooltips on (non-empty) selection. As for prefix removal, I'd ask you to file separate issue if possible (since it's not directly related and I'm still on the fence on that one, because it may get confusing -- consider e.g.  `Data.ByteString` vs `Data.ByteString.Lazy`)

**Comment by lierdakil** [comment]
@rvion, I've added experimental support for 'show type on selection'. It's disabled by default. To enable, see 'showTypeOnSelection' option in haskell-ghc-mod. Feel free to file new issues if something doesn't work right.

**Comment by rvion** [comment]
@lierdakil big thanks !!

**Comment by lierdakil** [comment]
For anyone interested, prefix hiding can be achieved with recent language-haskell using something like this in your stylesheet (provided syntax highlighting in tooltips is enabled):
```less
ide-haskell-tooltip .hint.haskell .module {
      display: inline-block;
      white-space: nowrap;
      width: 1ex;
      overflow-x: hidden;
      vertical-align: bottom;
      position: relative;
      &::before {
        content: "_";
      }
}
```

You can also make it show prefix on mouseover with something like
```less
ide-haskell-tooltip .hint.haskell .module {
      display: inline-block;
      white-space: nowrap;
      width: 1ex;
      overflow-x: hidden;
      vertical-align: bottom;
      position: relative;
      &::before {
        content: "_";
      }
      //show on hover
      pointer-events: auto;
      &:hover {
        &::before {
          content: none;
        }
        width: initial;
      }
}
```
