### ISSUE TITLE
infix keywords not highlighted

### ISSUE THREAD

**Issue by owestphal** [atom-haskell/ide-haskell#139]
Apparently the keywords `infix`, infixl` and infixr` just get highlighted as plain text.

**Comment by lierdakil** [comment]
Those are marked as `keyword.operator`. If your syntax theme doesn't highlight those, that's an issue with your syntax theme, basically. But you could override it with something like this in your stylesheet:

```less
atom-text-editor::shadow {
  .source.haskell {
    .keyword.operator {
      color: #CF8C00;
      &.infix {
        color: #CC77AC
      }
    }
  }
}
```
